In [1]:
import requests
import pandas as pd
import random
import time
import json



def get_data(url):
    response = requests.get(url) 
    if response.status_code == 200:
        return response.json()
    else:
        return None

def get_df(data):
    if data:
        return pd.DataFrame(pd.json_normalize(data['results']))
    else:
        return None

In [2]:
def get_places(location):
    results = []
    next_page_token = None
    for i in range(3):
        if i == 0:
            url = f"https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={location}&radius=1500&type=restaurant&key=AIzaSyCTikq4DDzQxEd2UfsgSr-S3ImmOfAvbt8"
        else:
            if next_page_token:
                url = f"{url}&pagetoken={next_page_token}"
            response = requests.get(url)
            data = json.loads(response.text)
            results += data['results']
            if 'next_page_token' in data:
                next_page_token = data['next_page_token']
            else:
                break
        time.sleep(2)
    return pd.json_normalize(results)

In [32]:
url = f"https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=40.483906740037675,-3.663253784179688&radius=1500&type=restaurant&keyword=closed&key=AIzaSyCTikq4DDzQxEd2UfsgSr-S3ImmOfAvbt8"

response = requests.get(url)

In [33]:
json.loads(response.text)

{'html_attributions': [],
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 40.4713833, 'lng': -3.676584699999999},
    'viewport': {'northeast': {'lat': 40.47270387989273,
      'lng': -3.675085220107278},
     'southwest': {'lat': 40.47000422010728, 'lng': -3.677784879892722}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'Restaurante El Bosco',
   'opening_hours': {'open_now': False},
   'photos': [{'height': 534,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/112709142374181637480">A Google User</a>'],
     'photo_reference': 'AfLeUgMzjfzavxRkU70a5YiY-wCZL4b6qkDTRRRuZF2BA-V_5AlnoxViDKKwy9RTjj9ghlE19JNnpSWDpu0d-vkIgEKzsWMxpgn0cljdH3a2ILeYS-3Ai34xuoCwpiLWTFus0riXJKs0xarHmSle0GR9mwurdwrP7mLIYvXq03bSC-K8CpKT',
     'width': 490}],
   'place_id': 'ChIJddtQPDkpQg0RipCUosFlXdE',
   'plus_code': {'compound_code': 'F8CF+H9 Madrid',
    'global_code': '8CGRF8CF+H9'},
   'price_level': 1,
   'rating': 4.5,
   'reference': 'ChIJddtQPDkpQg0RipCUosFlXdE',
   'scope': 'GOOGLE',
   'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
   'user_ratings_total': 279,
   'vicinity': 'C. de la Buganvilla, 2, Madrid'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 40.4871461, 'lng': -3.6648179},
    'viewport': {'northeast': {'lat': 40.48851787989272,
      'lng': -3.663545970107279},
     'southwest': {'lat': 40.48581822010728, 'lng': -3.666245629892722}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png',
   'icon_background_color': '#FF9E67',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet',
   'name': 'Delisko Manoteras',
   'opening_hours': {'open_now': False},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111343694503075576120">amoulet69</a>'],
     'photo_reference': 'AfLeUgM0pbwNZsfep_G020qq-UPipLY8j5Q4ltGBov2C1c8UH73tQrCfC8DjSA58HgktXRvIpH3sB6fWZSp3j12CIT8toiIRZQZt-0mrveKDUtDz535z_4pynGCFav7YpGBIAxDuD59eWNA9sEwfcruu5PARBZeCLhkbUNoi4EA1jsjgBY-v',
     'width': 4032}],
   'place_id': 'ChIJ4bxC91IpQg0RfBkEFenw-1w',
   'plus_code': {'compound_code': 'F8PP+V3 Madrid',
    'global_code': '8CGRF8PP+V3'},
   'price_level': 1,
   'rating': 3.7,
   'reference': 'ChIJ4bxC91IpQg0RfBkEFenw-1w',
   'scope': 'GOOGLE',
   'types': ['restaurant', 'food', 'point_of_interest', 'establishment'],
   'user_ratings_total': 169,
   'vicinity': 'Av. de Manoteras, 44, Madrid'}],
 'status': 'OK'}

In [ ]:
location = '40.483906740037675,-3.663253784179688'

In [ ]:
a = get_places(location)

In [ ]:
a['name'].nunique()

In [ ]:
location = '40.47708444297618,-3.6456155776977544'
b = get_places(location)
b

In [ ]:
b['name'].nunique()

In [ ]:
list=['40.47708444297618,-3.6456155776977544',
      '40.483906740037675,-3.663253784179688',
      '40.47019615747793,-3.5868644714355473',
      '40.4479268187739,-3.607549667358399',
      '40.42551942170478,-3.548069000244141',
      '40.43257561752109,-3.6079788208007812',
      '40.4090520858275,-3.6157035827636723',
      '40.353346961916685,-3.5303878784179688',
      '40.30099975681217,-3.4385490417480473',
      '40.36027992037527,-3.5923576354980473',
      '40.37924380501843,-3.6198234558105473',
      '40.3775438124365,-3.6550140380859375',
      '40.35164631606429,-3.684024810791016',
      '40.34144154031401,-3.690547943115235',
      '40.356878935492404,-3.6955261230468754',
      '40.345628301754054,-3.708915710449219',
      '40.34026396683983,-3.7115764617919926',
      '40.36479250084014,-3.7019634246826176',
      '40.372018540307586,-3.7518310546875004',
      '40.375909163733134,-3.7341499328613286',
      '40.373947532940626,-3.766250610351563',
      '40.38264366149726,-3.771915435791016',
      '40.40441175155707,-3.7458229064941406',
      '40.39362664052989,-3.73311996459961',
      '40.388266124513905,-3.723850250244141',
      '40.373947532940626,-3.766250610351563',
      '40.38486655180834,-3.7137222290039067',
      '40.38891986882411,-3.699302673339844',
      '40.41258113995309,-3.725910186767578',
      '40.47842284299747,-3.7284851074218754',
      '40.49043460477457,-3.7041091918945317',
      '40.50139998815443,-3.681449890136719',
      '40.47685593298893,-3.7033796310424805',
      '40.47558279167984,-3.71569633483886761',
      '40.46941261105147,-3.696126937866211',
      '40.46575594018434,-3.6896038055419926',
      '40.46020525575815,-3.6984443664550786',
      '40.45651542940327,-3.711962699890137',
      '40.4544581815914,-3.7026929855346684',
      '40.448286060225556,-3.703722953796387',
      '40.44593462678334,-3.713593482971192',
      '40.445869308013364,-3.719086647033692',
      '40.4388798328576,-3.7129068374633794',
      '40.432836943889086,-3.7179279327392583',
      '40.4298642965268,-3.71114730834961',
      '40.42659749953421,-3.7132501602172856',
      '40.420782208289914,-3.7104606628417973',
      '40.415652573463255,-3.711962699890137',
      '40.41055522409894,-3.7026929855346684'
      '40.40444443108599,-3.7109756469726567',
      '40.40081690651834,-3.6996459960937504',
      '40.39117523798271,-3.694968223571778',    
      
]

In [3]:
def get_places_new(locations):
    all_results = []
    for location in locations:
        results = []
        next_page_token = None
        for i in range(3):
            if i == 0:
                url = f"https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={location}&radius=600&type=restaurant&key=AIzaSyCTikq4DDzQxEd2UfsgSr-S3ImmOfAvbt8"
            else:
                if next_page_token:
                    url = f"{url}&pagetoken={next_page_token}"
                response = requests.get(url)
                data = json.loads(response.text)
                results += data['results']
                if 'next_page_token' in data:
                    next_page_token = data['next_page_token']
                else:
                    break
            time.sleep(2)
        df = pd.json_normalize(results)
        all_results.append(df)
    return pd.concat(all_results, ignore_index=True)

In [ ]:
a = get_places_new(list)

In [ ]:
a['place_id'].nunique()

In [ ]:
a.to_csv('google_data_0.csv')

In [3]:
import random

def generate_coordinates(n):
    coordinates = []
    for i in range(n):
        latitude = random.uniform(40.474, 40.376)
        longitude = random.uniform(-3.599, -3.737)
        coordinates.append("{:.14f},{:.14f}".format(latitude, longitude))
    return coordinates

In [5]:
another_list = generate_coordinates(300)

In [ ]:
new_df = get_places_new(new_list)

In [ ]:
new_df.shape

In [ ]:
new_df['place_id'].nunique()

In [ ]:
new_df.to_csv('new_df.csv')

In [ ]:
last_df = get_places_new(last_list)

In [ ]:
last_df.head()

In [ ]:
last_df['place_id'].nunique()

In [ ]:
last_df.to_csv('lastgoogle.csv')

In [ ]:
big_list=generate_coordinates(1000)

In [ ]:
huge_df = get_places_new(big_list)

In [ ]:
huge_df.shape

In [ ]:
huge_df['place_id'].nunique()

In [ ]:
huge_df.drop_duplicates(subset='place_id',inplace=True)

In [ ]:
huge_df.to_csv('huge_df.csv')

# Last call

In [6]:
df_last = get_places_new(ult_list)
df_last.shape

(2000, 24)

In [7]:
df_last['place_id'].nunique()

916

In [8]:
df_last.drop_duplicates(subset='place_id',inplace=True)

In [9]:
df_last

,business_status,icon,icon_background_color,icon_mask_base_uri,name,photos,place_id,price_level,rating,reference,...,geometry.location.lat,geometry.location.lng,geometry.viewport.northeast.lat,geometry.viewport.northeast.lng,geometry.viewport.southwest.lat,geometry.viewport.southwest.lng,opening_hours.open_now,plus_code.compound_code,plus_code.global_code,permanently_closed
0,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,https://maps.gstatic.com/mapfiles/place_api/ic...,Fogg Bar Birras & Burgers,"[{'height': 1080, 'html_attributions': ['<a hr...",ChIJv9OX-RkmQg0RPfsrHa2xQx8,1.0,4.7,ChIJv9OX-RkmQg0RPfsrHa2xQx8,...,40.408062,-3.676486,40.409458,-3.675102,40.406761,-3.677800,False,"C85F+6C Madrid, Spain",8CGRC85F+6C,NaN
1,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,https://maps.gstatic.com/mapfiles/place_api/ic...,Taberna Restaurante Murciano El Caldero,"[{'height': 1080, 'html_attributions': ['<a hr...",ChIJjRX4kBcmQg0RC9bGOuAEt4U,2.0,4.0,ChIJjRX4kBcmQg0RC9bGOuAEt4U,...,40.402573,-3.680895,40.403888,-3.679469,40.401190,-3.682167,True,"C839+2J Madrid, Spain",8CGRC839+2J,NaN
2,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,https://maps.gstatic.com/mapfiles/place_api/ic...,La Dehesa II,"[{'height': 1836, 'html_attributions': ['<a hr...",ChIJHTQKwxsmQg0RgaLz__xz3K0,NaN,3.8,ChIJHTQKwxsmQg0RgaLz__xz3K0,...,40.407160,-3.676736,40.408559,-3.675327,40.405861,-3.678025,True,"C84F+V8 Madrid, Spain",8CGRC84F+V8,NaN
3,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,https://maps.gstatic.com/mapfiles/place_api/ic...,Bodegas Rosell,"[{'height': 1536, 'html_attributions': ['<a hr...",ChIJ01bKOiUmQg0RMZVrsXwQifE,2.0,4.3,ChIJ01bKOiUmQg0RMZVrsXwQifE,...,40.403808,-3.690925,40.405148,-3.689461,40.402450,-3.692159,False,"C835+GJ Madrid, Spain",8CGRC835+GJ,NaN
4,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,https://maps.gstatic.com/mapfiles/place_api/ic...,Restaurante Don Giovanni,"[{'height': 367, 'html_attributions': ['<a hre...",ChIJPbyU3RgmQg0RbSQgBVIAsqQ,3.0,4.2,ChIJPbyU3RgmQg0RbSQgBVIAsqQ,...,40.407712,-3.680193,40.408853,-3.679053,40.406155,-3.681751,False,"C859+3W Madrid, Spain",8CGRC859+3W,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1992,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,https://maps.gstatic.com/mapfiles/place_api/ic...,Tony Roma's,"[{'height': 720, 'html_attributions': ['<a hre...",ChIJNy4mNoYoQg0RAulY3ZLXYQI,2.0,4.3,ChIJNy4mNoYoQg0RAulY3ZLXYQI,...,40.421817,-3.699914,40.423186,-3.698557,40.420488,-3.701255,True,"C8C2+P2 Madrid, Spain",8CGRC8C2+P2,NaN
1993,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,https://maps.gstatic.com/mapfiles/place_api/ic...,Restaurante El Cocinillas,"[{'height': 2000, 'html_attributions': ['<a hr...",ChIJlXWHRIgoQg0RfQ8rfV_A-yk,2.0,4.3,ChIJlXWHRIgoQg0RfQ8rfV_A-yk,...,40.424656,-3.701226,40.426023,-3.699865,40.423325,-3.702563,False,"C7FX+VG Madrid, Spain",8CGRC7FX+VG,NaN
1996,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,https://maps.gstatic.com/mapfiles/place_api/ic...,La Tasquita de Enfrente,"[{'height': 532, 'html_attributions': ['<a hre...",ChIJoQ2oZX0oQg0R6nFdo0cK4vs,4.0,4.2,ChIJoQ2oZX0oQg0R6nFdo0cK4vs,...,40.421287,-3.703527,40.422651,-3.702184,40.419953,-3.704882,False,"C7CW+GH Madrid, Spain",8CGRC7CW+GH,NaN
1997,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,https://maps.gstatic.com/mapfiles/place_api/ic...,Ribeira do Miño,"[{'height': 2992, 'html_attributions': ['<a hr...",ChIJ5clP9YgoQg0RPPKjDCT2wbo,1.0,4.4,ChIJ5clP9YgoQg0RPPKjDCT2wbo,...,40.424471,-3.700400,40.425809,-3.698972,40.423111,-3.701670,True,"C7FX+QR Madrid, Spain",8CGRC7FX+QR,NaN
1999,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,https://maps.gstatic.com/mapfiles/place_api/ic...,Alcuzcuz de Alhuzema,"[{'height': 480, 'html_attributions': ['<a hre...",ChIJ5Xo-kIgoQg0RYezdhSARgI8,2.0,4.2,ChIJ5Xo-kIgoQg0RYezdhSARgI8,...,40.423892,-3.699667,40.425252,-3.698337,40.422554,-3.701035,False,"C8F2+H4 Madrid, Spain",8CGRC8F2+H4,NaN

# Another call

In [6]:
df_a = get_places_new(another_list)
df_a.shape

(9029, 24)

In [7]:
df_a['place_id'].nunique()

4150

In [8]:
df_a.drop_duplicates(subset='place_id',inplace=True)

In [9]:
last_list = df_a['place_id'].tolist()

In [12]:
details_df = get_place_details(last_list)

In [13]:
details_df.head()

,html_attributions,status,result.address_components,result.adr_address,result.business_status,result.current_opening_hours.open_now,result.current_opening_hours.periods,result.current_opening_hours.weekday_text,result.delivery,result.dine_in,...,result.utc_offset,result.vicinity,result.website,result.wheelchair_accessible_entrance,result.curbside_pickup,result.editorial_summary.language,result.editorial_summary.overview,result.permanently_closed,result.secondary_opening_hours,result.current_opening_hours.special_days
0,[],OK,"[{'long_name': '29', 'short_name': '29', 'type...","<span class=""street-address"">C. de la Pilarica...",OPERATIONAL,False,"[{'close': {'date': '2023-02-26', 'day': 0, 't...","[Monday: 11:30 AM – 6:00 PM, Tuesday: Closed, ...",True,True,...,60,"Calle de la Pilarica, 29, Madrid",http://www.laparrillausera.com/,True,NaN,NaN,NaN,NaN,NaN,NaN
1,[],OK,"[{'long_name': '4', 'short_name': '4', 'types'...","<span class=""street-address"">C. de Dolores Bar...",OPERATIONAL,True,"[{'close': {'date': '2023-02-27', 'day': 1, 't...","[Monday: 7:30 AM – 12:00 AM, Tuesday: 2:00 – 2...",True,True,...,60,"Calle de Dolores Barranco, 4, Madrid",http://www.abarcamuxia.com/,True,NaN,NaN,NaN,NaN,NaN,NaN
2,[],OK,"[{'long_name': '92', 'short_name': '92', 'type...","<span class=""street-address"">C. del Olvido, 92...",OPERATIONAL,False,"[{'close': {'date': '2023-02-26', 'day': 0, 't...","[Monday: 12:00 – 5:00 PM, 7:00 – 11:30 PM, Tue...",False,True,...,60,"Calle del Olvido, 92, Madrid",http://www.royalcantonesmadrid.com/,True,False,en,"Dim sum plus classic Cantonese soups, meat, ri...",NaN,NaN,NaN
3,[],OK,"[{'long_name': '108', 'short_name': '108', 'ty...","<span class=""street-address"">C. de Ramón Luján...",OPERATIONAL,True,"[{'close': {'date': '2023-02-26', 'day': 0, 't...","[Monday: Closed, Tuesday: 8:00 AM – 12:00 AM, ...",False,True,...,60,"Calle de Ramón Luján, 108, Madrid",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],OK,"[{'long_name': '64', 'short_name': '64', 'type...","<span class=""street-address"">C. del Santuario,...",CLOSED_TEMPORARILY,NaN,NaN,NaN,NaN,True,...,60,"Calle del Santuario, 64, Madrid",NaN,NaN,NaN,NaN,NaN,True,NaN,NaN

In [14]:
details_df

,html_attributions,status,result.address_components,result.adr_address,result.business_status,result.current_opening_hours.open_now,result.current_opening_hours.periods,result.current_opening_hours.weekday_text,result.delivery,result.dine_in,...,result.utc_offset,result.vicinity,result.website,result.wheelchair_accessible_entrance,result.curbside_pickup,result.editorial_summary.language,result.editorial_summary.overview,result.permanently_closed,result.secondary_opening_hours,result.current_opening_hours.special_days
0,[],OK,"[{'long_name': '29', 'short_name': '29', 'type...","<span class=""street-address"">C. de la Pilarica...",OPERATIONAL,False,"[{'close': {'date': '2023-02-26', 'day': 0, 't...","[Monday: 11:30 AM – 6:00 PM, Tuesday: Closed, ...",True,True,...,60,"Calle de la Pilarica, 29, Madrid",http://www.laparrillausera.com/,True,NaN,NaN,NaN,NaN,NaN,NaN
1,[],OK,"[{'long_name': '4', 'short_name': '4', 'types'...","<span class=""street-address"">C. de Dolores Bar...",OPERATIONAL,True,"[{'close': {'date': '2023-02-27', 'day': 1, 't...","[Monday: 7:30 AM – 12:00 AM, Tuesday: 2:00 – 2...",True,True,...,60,"Calle de Dolores Barranco, 4, Madrid",http://www.abarcamuxia.com/,True,NaN,NaN,NaN,NaN,NaN,NaN
2,[],OK,"[{'long_name': '92', 'short_name': '92', 'type...","<span class=""street-address"">C. del Olvido, 92...",OPERATIONAL,False,"[{'close': {'date': '2023-02-26', 'day': 0, 't...","[Monday: 12:00 – 5:00 PM, 7:00 – 11:30 PM, Tue...",False,True,...,60,"Calle del Olvido, 92, Madrid",http://www.royalcantonesmadrid.com/,True,False,en,"Dim sum plus classic Cantonese soups, meat, ri...",NaN,NaN,NaN
3,[],OK,"[{'long_name': '108', 'short_name': '108', 'ty...","<span class=""street-address"">C. de Ramón Luján...",OPERATIONAL,True,"[{'close': {'date': '2023-02-26', 'day': 0, 't...","[Monday: Closed, Tuesday: 8:00 AM – 12:00 AM, ...",False,True,...,60,"Calle de Ramón Luján, 108, Madrid",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],OK,"[{'long_name': '64', 'short_name': '64', 'type...","<span class=""street-address"">C. del Santuario,...",CLOSED_TEMPORARILY,NaN,NaN,NaN,NaN,True,...,60,"Calle del Santuario, 64, Madrid",NaN,NaN,NaN,NaN,NaN,True,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4145,[],OK,"[{'long_name': '36', 'short_name': '36', 'type...","<span class=""street-address"">Calle del Marqués...",OPERATIONAL,True,"[{'close': {'date': '2023-02-26', 'day': 0, 't...","[Monday: 1:00 – 5:00 PM, 7:30 – 11:00 PM, Tues...",True,True,...,60,"Calle del Marqués de Viana, 36, Madrid",https://rinconcitocuzqueno.com/,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4146,[],OK,"[{'long_name': '5', 'short_name': '5', 'types'...","<span class=""street-address"">C. Félix Boix, 5<...",OPERATIONAL,False,"[{'close': {'date': '2023-02-26', 'day': 0, 't...","[Monday: 1:00 – 4:30 PM, 8:30 PM – 1:00 AM, Tu...",False,True,...,60,"Calle Félix Boix, 5, Madrid",http://demariarestaurante.es/,True,NaN,NaN,NaN,NaN,NaN,NaN
4147,[],OK,"[{'long_name': '6', 'short_name': '6', 'types'...","<span class=""street-address"">C. Félix Boix, 6<...",OPERATIONAL,True,"[{'close': {'date': '2023-02-28', 'day': 2, 't...","[Monday: 7:00 AM – 2:00 AM, Tuesday: 7:00 AM –...",NaN,True,...,60,"Calle Félix Boix, 6, Madrid",http://www.restauranterastmadrid.com/,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4148,[],OK,"[{'long_name': '9', 'short_name': '9', 'types'...","<span class=""street-address"">C. Félix Boix, 9<...",OPERATIONAL,True,"[{'close': {'date': '2023-02-27', 'day': 1, 't...","[Monday: 1:00 PM – 1:00 AM, Tuesday: 1:00 PM –...",NaN,True,...,60,"Calle Félix Boix, 9, Madrid",https://www.knightnsquire.es/,NaN,NaN,en,Casual joint festooned with cinema memorabilia...,NaN,"[{'open_now': False, 'periods': [{'close': {'d...",NaN
4149,[],OK,"[{'long_name': '1', 'short_name': '1', 'types'...","<span class=""street-address"">C. de José Castán...",OPERATIONAL,True,"[{'close': {'date': '2023-02-26', 'day': 0, 't...","[Monday: Closed, Tuesday: 8:00 AM – 11:00 PM, ...",False,True,...,60,"Calle de José Castán Tobeñas, 1, Madrid",https://casasotero.org/,True,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
details_df.drop(columns=['html_attributions', 'status','result.secondary_opening_hours',
        'result.adr_address', 'result.current_opening_hours.open_now','result.geometry.location.lat',
       'result.geometry.location.lng','result.geometry.viewport.northeast.lat',
       'result.geometry.viewport.northeast.lng','result.geometry.viewport.southwest.lat',
       'result.geometry.viewport.southwest.lng', 'result.icon','result.icon_background_color', 
        'result.icon_mask_base_uri',
       'result.permanently_closed','result.curbside_pickup',
       'result.editorial_summary.language','result.editorial_summary.overview'],axis=1,inplace=True)

In [16]:
details_df.head()

,result.address_components,result.business_status,result.current_opening_hours.periods,result.current_opening_hours.weekday_text,result.delivery,result.dine_in,result.formatted_address,result.formatted_phone_number,result.international_phone_number,result.name,...,result.serves_wine,result.takeout,result.types,result.url,result.user_ratings_total,result.utc_offset,result.vicinity,result.website,result.wheelchair_accessible_entrance,result.current_opening_hours.special_days
0,"[{'long_name': '29', 'short_name': '29', 'type...",OPERATIONAL,"[{'close': {'date': '2023-02-26', 'day': 0, 't...","[Monday: 11:30 AM – 6:00 PM, Tuesday: Closed, ...",True,True,"C. de la Pilarica, 29, 28026 Madrid, Spain",914 76 27 81,+34 914 76 27 81,La Parrilla de Usera,...,True,True,"[restaurant, food, point_of_interest, establis...",https://maps.google.com/?cid=17198940248734380063,1072.0,60,"Calle de la Pilarica, 29, Madrid",http://www.laparrillausera.com/,True,NaN
1,"[{'long_name': '4', 'short_name': '4', 'types'...",OPERATIONAL,"[{'close': {'date': '2023-02-27', 'day': 1, 't...","[Monday: 7:30 AM – 12:00 AM, Tuesday: 2:00 – 2...",True,True,"C. de Dolores Barranco, 4, 28026 Madrid, Spain",914 76 94 03,+34 914 76 94 03,A'barca Muxia,...,True,True,"[restaurant, point_of_interest, food, establis...",https://maps.google.com/?cid=9721905327553626747,1190.0,60,"Calle de Dolores Barranco, 4, Madrid",http://www.abarcamuxia.com/,True,NaN
2,"[{'long_name': '92', 'short_name': '92', 'type...",OPERATIONAL,"[{'close': {'date': '2023-02-26', 'day': 0, 't...","[Monday: 12:00 – 5:00 PM, 7:00 – 11:30 PM, Tue...",False,True,"C. del Olvido, 92, 28026 Madrid, Spain",915 00 01 61,+34 915 00 01 61,Royal Cantonés,...,True,True,"[restaurant, food, point_of_interest, establis...",https://maps.google.com/?cid=4856136259285874099,2837.0,60,"Calle del Olvido, 92, Madrid",http://www.royalcantonesmadrid.com/,True,NaN
3,"[{'long_name': '108', 'short_name': '108', 'ty...",OPERATIONAL,"[{'close': {'date': '2023-02-26', 'day': 0, 't...","[Monday: Closed, Tuesday: 8:00 AM – 12:00 AM, ...",False,True,"C. de Ramón Luján, 108, 28026 Madrid, Spain",NaN,NaN,Bar La estrella,...,True,True,"[bar, restaurant, food, point_of_interest, est...",https://maps.google.com/?cid=2608349744074711146,121.0,60,"Calle de Ramón Luján, 108, Madrid",NaN,NaN,NaN
4,"[{'long_name': '64', 'short_name': '64', 'type...",CLOSED_TEMPORARILY,NaN,NaN,NaN,True,"C. del Santuario, 64, 28026 Madrid, Spain",NaN,NaN,Mahou,...,NaN,NaN,"[bar, restaurant, food, point_of_interest, est...",https://maps.google.com/?cid=11021975118473495022,5.0,60,"Calle del Santuario, 64, Madrid",NaN,NaN,NaN

In [27]:
pla_det = pd.concat([details_df,details_df2], axis=0, ignore_index=True)

In [17]:
places=pd.read_csv('/Users/Usuario/demo/Ironhack/Final_Project/raw_data/google_data/new_places.csv')
places.drop('Unnamed: 0', axis=1, inplace=True)

In [18]:
places_new = pd.concat([places, details_df], axis=0, ignore_index=True)

In [19]:
places_new.drop_duplicates(subset='result.place_id',inplace=True)

In [20]:
places_new.reset_index(drop=True, inplace=True)

In [23]:
places_new.shape

(6308, 38)

In [24]:
places_new.to_csv('brand_new_places.csv')

# Place details

In [ ]:
url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJQRD8AUYxQg0RsFS60jZJK40&key=AIzaSyCTikq4DDzQxEd2UfsgSr-S3ImmOfAvbt8"

In [ ]:
pd.json_normalize(get_data(url)['result']).columns

In [4]:
import requests
import pandas as pd

def get_place_details(place_ids):
    base_url = "https://maps.googleapis.com/maps/api/place/details/json?"
    df_list = []

    for place_id in place_ids:
        url = base_url + f"place_id={place_id}&key=AIzaSyASsUGkw9ee_NHDRQj-BuBut_3CKUn_2Do"
        response = requests.get(url)
        data = response.json()

        # You can access the data returned from the API here and add it to a list of dataframes
        df_list.append(pd.json_normalize(data))

    # Concatenate all dataframes into one
    result = pd.concat(df_list, ignore_index=True)
    return result

In [ ]:
data = pd.read_csv("/Users/Usuario/demo/Ironhack/Final_Project/google_data/database.csv")

In [ ]:
dataset = pd.concat([huge_df,data], axis=0, ignore_index=True)

In [ ]:
dataset = dataset.drop_duplicates(subset='place_id')

In [ ]:
dataset.to_csv('place_search.csv')

In [ ]:
place_id_list = dataset['place_id'].tolist()

In [ ]:
place_details_df = get_place_details(place_id_list)

In [ ]:
place_details_df.shape

In [ ]:
place_details_df.to_csv('place_details.csv')

In [ ]:
pd.set_option('display.max_columns',100)

In [ ]:
dataset.columns

In [ ]:
dataset.drop(columns=['Unnamed: 0.1', 'Unnamed: 0', 'formatted_address',
       'icon', 'icon_background_color', 'icon_mask_base_uri', 'geometry.location.lat', 'geometry.location.lng',
       'geometry.viewport.northeast.lat', 'geometry.viewport.northeast.lng', 'photos',
       'geometry.viewport.southwest.lat', 'geometry.viewport.southwest.lng',
       'opening_hours.open_now', 'plus_code.compound_code',
       'plus_code.global_code', 'level_0', 'index', 'scope', 
       'permanently_closed'],axis=1,inplace=True)
dataset.head()

In [ ]:
data['vicinity'].isna().sum()/data['vicinity'].shape[0]

In [ ]:
place_details_df.columns

In [ ]:
place_details_df.head()

In [ ]:
place_details_df = place_details_df.drop(columns=['html_attributions', 'status','result.secondary_opening_hours',
        'result.adr_address', 'result.current_opening_hours.open_now','result.geometry.location.lat',
       'result.geometry.location.lng','result.geometry.viewport.northeast.lat',
       'result.geometry.viewport.northeast.lng','result.geometry.viewport.southwest.lat',
       'result.geometry.viewport.southwest.lng', 'result.icon','result.icon_background_color', 
        'result.icon_mask_base_uri', 'result.current_opening_hours.special_days',
       'result.permanently_closed', 'error_message','result.curbside_pickup',
       'result.editorial_summary.language','result.editorial_summary.overview'],axis=1)

In [ ]:
place_details_df.to_csv('place_details.csv')

In [ ]:
place_details_df.isna().sum()

In [8]:
last_search = ['40.476921221636104,-3.6839389801025395','40.46562534111409,-3.689346313476563','40.45883383953704,-3.6900329589843754','40.45171508652637,-3.690719604492188','40.44374641343403,-3.6972427368164067',
'40.433555586164566,-3.704280853271485','40.42623814217773,-3.7068557739257817','40.41780902810895,-3.709516525268555','40.41114339950097,-3.7083148956298833','40.41218903196705,-3.6992168426513676',
'40.41228705917777,-3.7044954299926762','40.42166433537493,-3.694539070129395','40.42208905910521,-3.7044954299926762','40.42610746629935,-3.7004184722900395',
'40.43107297119672,-3.6970710754394536','40.43489485354759,-3.6987018585205083','40.44247264450351,-3.6973714828491215','40.44802479390569,-3.698487281799317',
'40.46307860848826,-3.683080673217774','40.4583766945754,-3.6767721176147465','40.45135586340433,-3.677630424499512','40.44439961890733,-3.6784458160400395','40.44645717465783,-3.670420646667481',
'40.43923912266282,-3.6718797683715825','40.433424924503925,-3.6734247207641606','40.427904237372694,-3.6689186096191406','40.42496404153376,-3.6801624298095708','40.41882188446544,-3.673810958862305',
'40.413986174807626,-3.669605255126953','40.407581591989015,-3.6700773239135747','40.40686267219694,-3.688573837280274','40.40787569332703,-3.700461387634278',
'40.41222170771984,-3.6990451812744145','40.42258320545491,-3.6970496177673344','40.42747955035998,-3.6825227737426762'               
]

In [9]:
last_search_df = get_places_new(last_search)

In [10]:
last_search_df.shape

(1400, 24)

In [11]:
last_search_df = last_search_df.drop_duplicates(subset='place_id')

In [12]:
last_search_df.shape

(808, 24)

In [13]:
details = last_search_df['place_id'].tolist()

In [14]:
last_df = get_place_details(details)

In [16]:
places = pd.read_csv('place_details.csv')
places.head()

,Unnamed: 0,result.address_components,result.business_status,result.current_opening_hours.periods,result.current_opening_hours.weekday_text,result.delivery,result.dine_in,result.formatted_address,result.formatted_phone_number,result.international_phone_number,...,result.serves_vegetarian_food,result.serves_wine,result.takeout,result.types,result.url,result.user_ratings_total,result.utc_offset,result.vicinity,result.website,result.wheelchair_accessible_entrance
0,0,"[{'long_name': '10', 'short_name': '10', 'type...",OPERATIONAL,"[{'close': {'date': '2023-02-13', 'day': 1, 't...",['Monday: 12:30\u202fPM\u2009–\u200912:00\u202...,True,True,"C. San Juan de Ortega, 10, 28050 Madrid, Spain",913 07 52 88,+34 913 07 52 88,...,False,True,True,"['restaurant', 'food', 'point_of_interest', 'e...",https://maps.google.com/?cid=13282398378271868427,1306.0,60.0,"Calle San Juan de Ortega, 10, Madrid",http://www.grupoladehesa.com/,True
1,1,"[{'long_name': '1', 'short_name': '1', 'types'...",OPERATIONAL,"[{'close': {'date': '2023-02-12', 'day': 0, 't...",['Monday: 10:00\u202fAM\u2009–\u200910:00\u202...,True,NaN,"C. de Margarita de Parma, 1, 28050 Madrid, Spain",913 84 82 00,+34 913 84 82 00,...,NaN,NaN,NaN,"['shopping_mall', 'cafe', 'meal_delivery', 'su...",https://maps.google.com/?cid=3737344296213236355,17570.0,60.0,"Calle de Margarita de Parma, 1, Madrid",https://www.elcorteingles.es/centroscomerciale...,True
2,2,"[{'long_name': 'Zona', 'short_name': 'Zona', '...",OPERATIONAL,"[{'close': {'date': '2023-02-12', 'day': 0, 't...","['Monday: Closed', 'Tuesday: 12:00\u2009–\u200...",True,True,"Paseo de la, Zona, P.º de la Tierra de Melide,...",917 50 53 93,+34 917 50 53 93,...,NaN,True,True,"['restaurant', 'food', 'point_of_interest', 'e...",https://maps.google.com/?cid=14070834893686348892,599.0,60.0,"Zona, Paseo de la, Paseo de la Tierra de Melid...",https://www.casacorrochano.es/,NaN
3,3,"[{'long_name': 'Plaza de la Moraleja', 'short_...",OPERATIONAL,"[{'close': {'date': '2023-02-13', 'day': 1, 't...",['Monday: 1:00\u202fPM\u2009–\u200912:00\u202f...,False,True,"Pl. de la Moraleja, 28109 Alcobendas, Madrid, ...",916 25 25 00,+34 916 25 25 00,...,False,True,True,"['restaurant', 'food', 'point_of_interest', 'e...",https://maps.google.com/?cid=16618770644644484753,597.0,60.0,"Plaza de la Moraleja, Alcobendas",https://restauranteaspen.com/,True
4,4,"[{'long_name': '1', 'short_name': '1', 'types'...",OPERATIONAL,"[{'close': {'date': '2023-02-13', 'day': 1, 't...",['Monday: 12:30\u202fPM\u2009–\u20092:00\u202f...,False,True,"Pl. de la Moraleja, 1, 28109 Alcobendas, Madri...",916 58 52 97,+34 916 58 52 97,...,False,True,True,"['restaurant', 'food', 'point_of_interest', 'e...",https://maps.google.com/?cid=5931455114014290729,2378.0,60.0,"Plaza de la Moraleja, 1, Alcobendas",https://lamaquinalamoraleja.es/,True

In [20]:
last_df.drop(columns=['html_attributions', 'status','result.secondary_opening_hours',
        'result.adr_address', 'result.current_opening_hours.open_now','result.geometry.location.lat',
       'result.geometry.location.lng','result.geometry.viewport.northeast.lat',
       'result.geometry.viewport.northeast.lng','result.geometry.viewport.southwest.lat',
       'result.geometry.viewport.southwest.lng', 'result.icon','result.icon_background_color', 
        'result.icon_mask_base_uri', 'result.current_opening_hours.special_days',
       'result.permanently_closed','result.curbside_pickup',
       'result.editorial_summary.language','result.editorial_summary.overview'],axis=1,inplace=True)

In [23]:
last_df.head()

,result.address_components,result.business_status,result.current_opening_hours.periods,result.current_opening_hours.weekday_text,result.dine_in,result.formatted_address,result.formatted_phone_number,result.international_phone_number,result.name,result.opening_hours.open_now,...,result.reservable,result.serves_beer,result.serves_brunch,result.serves_dinner,result.serves_lunch,result.takeout,result.website,result.wheelchair_accessible_entrance,result.serves_breakfast,result.serves_vegetarian_food
0,"[{'long_name': 'Torre Espacio', 'short_name': ...",OPERATIONAL,"[{'close': {'date': '2023-02-13', 'day': 1, 't...","[Monday: 1:30 – 3:30 PM, Tuesday: 1:30 – 3:30 ...",True,"Torre Espacio, P.º de la Castellana, 259D, 280...",914 27 68 91,+34 914 27 68 91,Espacio 33,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'long_name': '260', 'short_name': '260', 'ty...",OPERATIONAL,"[{'close': {'date': '2023-02-12', 'day': 0, 't...","[Monday: 12:30 PM – 2:00 AM, Tuesday: 12:30 PM...",True,"P.º de la Castellana, 260, 28046 Madrid, Spain",913 23 84 10,+34 913 23 84 10,Casa Nemesio,False,...,True,True,True,True,True,True,https://casanemesio.es/,True,NaN,NaN
2,"[{'long_name': '259B', 'short_name': '259B', '...",OPERATIONAL,"[{'close': {'date': '2023-02-14', 'day': 2, 't...","[Monday: Closed, Tuesday: 1:30 – 4:00 PM, 8:30...",True,"P.º de la Castellana, 259B, 28046 Madrid, Spain",913 34 27 55,+34 913 34 27 55,Restaurante Volvoreta,False,...,True,True,True,True,True,False,https://www.restaurantevolvoretamadrid.com/?td...,True,True,False
3,"[{'long_name': '27', 'short_name': '27', 'type...",OPERATIONAL,"[{'close': {'date': '2023-02-12', 'day': 0, 't...","[Monday: 12:00 AM – 12:00 PM, 12:30 – 4:30 PM,...",True,"C. de Agustín de Foxá, 27, 28036 Madrid, Spain",913 14 78 18,+34 913 14 78 18,Asia Té,False,...,True,True,True,True,True,True,http://asiate.eu/,NaN,NaN,NaN
4,"[{'long_name': '274', 'short_name': '274', 'ty...",OPERATIONAL,"[{'close': {'date': '2023-02-12', 'day': 0, 't...","[Monday: 7:30 AM – 10:00 PM, Tuesday: 7:30 AM ...",True,"P.º de la Castellana, 274, 28046 Madrid, Spain",913 44 91 77,+34 913 44 91 77,Rodilla,True,...,False,True,True,True,True,True,https://www.rodilla.es/?utm_source=google&utm-...,True,True,False

In [28]:
places.drop('Unnamed: 0',axis=1,inplace=True)

In [30]:
places_df = pd.concat([places, last_df], axis=0, ignore_index=True)

In [33]:
places_df = places_df.drop_duplicates(subset='result.place_id')

In [34]:
places_df.shape

(3843, 37)

In [35]:
places_df.to_csv('places_df.csv')

In [ ]:
all_google_data = pd.merge(data, place_details_df, left_on='place_id', right_on='result.place_id', how='right')

In [ ]:
#all_google_data.dropna(how='all', inplace=True)

In [ ]:
pd.set_option('display.max_rows',100)

In [ ]:
all_google_data.drop(columns=['result.editorial_summary.language','result.editorial_summary.overview',
                              'result.curbside_pickup', 'result.price_level','result.user_ratings_total'],axis=1,inplace=True)

In [ ]:
all_google_data.columns

In [ ]:
all_google_data.to_csv('all_google_data.csv')

# Last places details search

In [12]:
last_details = df_last['place_id'].tolist()

In [13]:
last_details_df = get_place_details(last_details)

In [14]:
last_details_df.shape

(916, 56)

In [15]:
last_details_df

,html_attributions,status,result.address_components,result.adr_address,result.business_status,result.current_opening_hours.open_now,result.current_opening_hours.periods,result.current_opening_hours.weekday_text,result.dine_in,result.formatted_address,...,result.serves_breakfast,result.serves_brunch,result.wheelchair_accessible_entrance,result.delivery,result.editorial_summary.language,result.editorial_summary.overview,result.curbside_pickup,result.secondary_opening_hours,result.permanently_closed,result.current_opening_hours.special_days
0,[],OK,"[{'long_name': '6', 'short_name': '6', 'types'...","<span class=""street-address"">Pl. de los Reyes ...",OPERATIONAL,False,"[{'close': {'date': '2023-02-19', 'day': 0, 't...","[Monday: Closed, Tuesday: Closed, Wednesday: 1...",True,"Pl. de los Reyes Magos, 6, 28007 Madrid, Spain",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],OK,"[{'long_name': '2', 'short_name': '2', 'types'...","<span class=""street-address"">Tr.ª de Téllez, 2...",OPERATIONAL,True,"[{'close': {'date': '2023-02-19', 'day': 0, 't...","[Monday: 9:00 AM – 4:00 PM, Tuesday: 9:00 AM –...",True,"Tr.ª de Téllez, 2, 28007 Madrid, Spain",...,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],OK,"[{'long_name': '12', 'short_name': '12', 'type...","<span class=""street-address"">Av. del Mediterrá...",OPERATIONAL,True,"[{'close': {'date': '2023-02-20', 'day': 1, 't...","[Monday: 9:30 AM – 12:00 AM, Tuesday: 9:30 AM ...",True,"Av. del Mediterráneo, 12, 28007 Madrid, Spain",...,True,True,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN
3,[],OK,"[{'long_name': '14', 'short_name': '14', 'type...","<span class=""street-address"">Calle del Gral. L...",OPERATIONAL,True,"[{'close': {'date': '2023-02-19', 'day': 0, 't...","[Monday: Closed, Tuesday: 12:00 – 4:00 PM, 7:0...",True,"Calle del Gral. Lacy, 14, 28045 Madrid, Spain",...,False,True,True,True,en,Classic Spanish eats & wines in a buzzy 1920s ...,NaN,NaN,NaN,NaN
4,[],OK,"[{'long_name': 'posterior', 'short_name': 'pos...","<span class=""street-address"">Paseo de la R. Cr...",OPERATIONAL,False,"[{'close': {'date': '2023-02-19', 'day': 0, 't...","[Monday: 1:30 – 4:00 PM, 8:30 – 11:00 PM, Tues...",True,"Paseo de la R. Cristina, 23, posterior, 28014 ...",...,NaN,True,True,True,en,Upscale trattoria specializing in truffle dish...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
911,[],OK,"[{'long_name': '34', 'short_name': '34', 'type...","<span class=""street-address"">C/ de Hortaleza, ...",OPERATIONAL,True,"[{'close': {'date': '2023-02-19', 'day': 0, 't...","[Monday: 12:00 – 11:30 PM, Tuesday: 12:00 – 11...",True,"C/ de Hortaleza, 34, 28004 Madrid, Spain",...,True,True,NaN,True,en,"Long-running, family-friendly steakhouse chain...",True,NaN,NaN,NaN
912,[],OK,"[{'long_name': '3', 'short_name': '3', 'types'...","<span class=""street-address"">C. de San Joaquín...",OPERATIONAL,False,"[{'close': {'date': '2023-02-19', 'day': 0, 't...","[Monday: Closed, Tuesday: Closed, Wednesday: C...",True,"C. de San Joaquín, 3, 28004 Madrid, Spain",...,True,NaN,NaN,False,en,Homey restaurant with bold coastal decor dishi...,NaN,NaN,NaN,NaN
913,[],OK,"[{'long_name': '6', 'short_name': '6', 'types'...","<span class=""street-address"">C. de la Ballesta...",OPERATIONAL,False,"[{'close': {'date': '2023-02-21', 'day': 2, 't...","[Monday: Closed, Tuesday: 1:30 – 4:00 PM, 8:00...",True,"C. de la Ballesta, 6, 28004 Madrid, Spain",...,False,NaN,NaN,True,en,Elegantly plated tasting menus celebrate seaso...,NaN,NaN,NaN,NaN
914,[],OK,"[{'long_name': '1', 'short_name': '1', 'types'...","<span class=""street-address"">Calle de Sta. Brí...",OPERATIONAL,True,"[{'close': {'date': '2023-02-20', 'day': 1, 't...","[Monday: Closed, Tuesday: 10:00 AM – 12:00 AM,...",True,"Calle de Sta. Brígida, 1, 28004 Madrid, Spain",...,False,True,True,NaN,en,"Menus of shellfish & crustaceans, plus wine, i...",NaN,NaN,NaN,NaN
915,[],OK,"[{'long_name': '8', 'short_name': '8', 'types'...","<span class=""street-address"">C. de la Farmacia...",OPERATIONAL,False,"[{'close': {'date': '2023-02-19', 'day': 0, 't...","[Monday: Closed, Tuesday: 1:30 – 4:30 PM, 8:30...",True,"C. de la Farmacia, 8, 28004 Madrid, Spain",...,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
last_details_df.drop(columns=['html_attributions', 'status','result.secondary_opening_hours',
        'result.adr_address', 'result.current_opening_hours.open_now','result.geometry.location.lat',
       'result.geometry.location.lng','result.geometry.viewport.northeast.lat',
       'result.geometry.viewport.northeast.lng','result.geometry.viewport.southwest.lat',
       'result.geometry.viewport.southwest.lng', 'result.icon','result.icon_background_color', 
        'result.icon_mask_base_uri', 'result.current_opening_hours.special_days',
       'result.permanently_closed','result.curbside_pickup',
       'result.editorial_summary.language','result.editorial_summary.overview'],axis=1,inplace=True)

In [17]:
last_details_df

,result.address_components,result.business_status,result.current_opening_hours.periods,result.current_opening_hours.weekday_text,result.dine_in,result.formatted_address,result.formatted_phone_number,result.international_phone_number,result.name,result.opening_hours.open_now,...,result.types,result.url,result.user_ratings_total,result.utc_offset,result.vicinity,result.website,result.serves_breakfast,result.serves_brunch,result.wheelchair_accessible_entrance,result.delivery
0,"[{'long_name': '6', 'short_name': '6', 'types'...",OPERATIONAL,"[{'close': {'date': '2023-02-19', 'day': 0, 't...","[Monday: Closed, Tuesday: Closed, Wednesday: 1...",True,"Pl. de los Reyes Magos, 6, 28007 Madrid, Spain",912 83 60 26,+34 912 83 60 26,Fogg Bar Birras & Burgers,False,...,"[restaurant, bar, food, point_of_interest, est...",https://maps.google.com/?cid=2252839595692260157,1055.0,60,"Plaza de los Reyes Magos, 6, Madrid",http://foggbar.es/,NaN,NaN,NaN,NaN
1,"[{'long_name': '2', 'short_name': '2', 'types'...",OPERATIONAL,"[{'close': {'date': '2023-02-19', 'day': 0, 't...","[Monday: 9:00 AM – 4:00 PM, Tuesday: 9:00 AM –...",True,"Tr.ª de Téllez, 2, 28007 Madrid, Spain",915 01 61 90,+34 915 01 61 90,Taberna Restaurante Murciano El Caldero,True,...,"[restaurant, food, point_of_interest, establis...",https://maps.google.com/?cid=9635175288887760395,944.0,60,"Travesía de Téllez, 2, Madrid",http://www.elcaldero.com/,True,True,True,NaN
2,"[{'long_name': '12', 'short_name': '12', 'type...",OPERATIONAL,"[{'close': {'date': '2023-02-20', 'day': 1, 't...","[Monday: 9:30 AM – 12:00 AM, Tuesday: 9:30 AM ...",True,"Av. del Mediterráneo, 12, 28007 Madrid, Spain",915 01 62 01,+34 915 01 62 01,La Dehesa II,True,...,"[restaurant, cafe, bar, store, food, point_of_...",https://maps.google.com/?cid=12528015793900987009,314.0,60,"Avenida del Mediterráneo, 12, Madrid",NaN,True,True,NaN,True
3,"[{'long_name': '14', 'short_name': '14', 'type...",OPERATIONAL,"[{'close': {'date': '2023-02-19', 'day': 0, 't...","[Monday: Closed, Tuesday: 12:00 – 4:00 PM, 7:0...",True,"Calle del Gral. Lacy, 14, 28045 Madrid, Spain",914 67 84 58,+34 914 67 84 58,Bodegas Rosell,True,...,"[bar, restaurant, food, point_of_interest, est...",https://maps.google.com/?cid=17404460362688599345,4490.0,60,"Calle del General Lacy, 14, Madrid",http://bodegasrosell.es/,False,True,True,True
4,"[{'long_name': 'posterior', 'short_name': 'pos...",OPERATIONAL,"[{'close': {'date': '2023-02-19', 'day': 0, 't...","[Monday: 1:30 – 4:00 PM, 8:30 – 11:00 PM, Tues...",True,"Paseo de la R. Cristina, 23, posterior, 28014 ...",914 34 83 38,+34 914 34 83 38,Restaurante Don Giovanni,False,...,"[restaurant, food, point_of_interest, establis...",https://maps.google.com/?cid=11867548320347989101,2601.0,60,"Paseo de la Reina Cristina, 23, posterior, Madrid",http://www.dongiovanni.es/,NaN,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
911,"[{'long_name': '34', 'short_name': '34', 'type...",OPERATIONAL,"[{'close': {'date': '2023-02-19', 'day': 0, 't...","[Monday: 12:00 – 11:30 PM, Tuesday: 12:00 – 11...",True,"C/ de Hortaleza, 34, 28004 Madrid, Spain",915 21 23 58,+34 915 21 23 58,Tony Roma's,True,...,"[meal_delivery, restaurant, food, point_of_int...",https://maps.google.com/?cid=171655286595578114,3091.0,60,"Calle de Hortaleza, 34, Madrid",https://tonyromas.es/,True,True,NaN,True
912,"[{'long_name': '3', 'short_name': '3', 'types'...",OPERATIONAL,"[{'close': {'date': '2023-02-19', 'day': 0, 't...","[Monday: Closed, Tuesday: Closed, Wednesday: C...",True,"C. de San Joaquín, 3, 28004 Madrid, Spain",915 23 29 60,+34 915 23 29 60,Restaurante El Cocinillas,False,...,"[restaurant, point_of_interest, food, establis...",https://maps.google.com/?cid=3025223091063820157,505.0,60,"Calle de San Joaquín, 3, Madrid",https://restauranteelcocinillas.es/,True,NaN,NaN,False
913,"[{'long_name': '6', 'short_name': '6', 'types'...",OPERATIONAL,"[{'close': {'date': '2023-02-21', 'day': 2, 't...","[Monday: Closed, Tuesday: 1:30 – 4:00 PM, 8:00...",True,"C. de la Ballesta, 6, 28004 Madrid, Spain",915 32 54 49,+34 915 32 54 49,La Tasquita de Enfrente,False,...,"[restaurant, food, point_of_interest, establis...",https://maps.google.com/?cid=18150080751056286186,536.0,60,"Calle de la Ballesta, 6, Madrid",http://www.latasquitadeenfrente.com/,False,NaN,NaN,True
914,"[{'long_name': '1', 'short_name': '1', 'types'...",OPERATIONAL,"[{'close': {'date': '2023-02-20', 'day': 1, 't...","[Monday: Closed, Tuesday: 10:00 AM – 12:00 AM,...",True,"Calle de Sta. Brígida, 1, 28004 Madrid, Spain",915 21 98 54,+34 915 21 98 54,Ribeira do Miño,True,...,"[restaurant, food, point_of_interest, establis...",https://maps.google.com/?cid=13457307796251079228,4990.0,60,"Calle de Santa Brígida, 1, Madrid",http://www.marisqueriaribeiradomino.com/,False,True,True,NaN
915,"[{'long_name': '8', 'short_name': '8', 'types'...",OPERATIONAL,"[{'close': {'date': '2023-02-19', 'day': 0, 't...","[Monday: Closed, Tuesday: 1:30 – 4:30 PM, 8:30...",True,"C. de la Farmacia, 8, 28004 Madrid, Spain",915 31 94 11,+34 915 31 94 11,Alcuzcuz de Alhuzema,False,...,"[restaurant, food, point_of_interest, establis...",https://maps.google.com/?cid=10340283575825198177,426.0,60,"Calle de la Farmacia, 8, Madrid",NaN,NaN,NaN,True,NaN

In [19]:
places = pd.read_csv('/Users/Usuario/demo/Ironhack/Final_Project/raw_data/google_data/places_df.csv')
places.head()

,Unnamed: 0,result.address_components,result.business_status,result.current_opening_hours.periods,result.current_opening_hours.weekday_text,result.delivery,result.dine_in,result.formatted_address,result.formatted_phone_number,result.international_phone_number,...,result.serves_vegetarian_food,result.serves_wine,result.takeout,result.types,result.url,result.user_ratings_total,result.utc_offset,result.vicinity,result.website,result.wheelchair_accessible_entrance
0,0,"[{'long_name': '10', 'short_name': '10', 'type...",OPERATIONAL,"[{'close': {'date': '2023-02-13', 'day': 1, 't...",['Monday: 12:30\u202fPM\u2009–\u200912:00\u202...,True,True,"C. San Juan de Ortega, 10, 28050 Madrid, Spain",913 07 52 88,+34 913 07 52 88,...,False,True,True,"['restaurant', 'food', 'point_of_interest', 'e...",https://maps.google.com/?cid=13282398378271868427,1306.0,60.0,"Calle San Juan de Ortega, 10, Madrid",http://www.grupoladehesa.com/,True
1,1,"[{'long_name': '1', 'short_name': '1', 'types'...",OPERATIONAL,"[{'close': {'date': '2023-02-12', 'day': 0, 't...",['Monday: 10:00\u202fAM\u2009–\u200910:00\u202...,True,NaN,"C. de Margarita de Parma, 1, 28050 Madrid, Spain",913 84 82 00,+34 913 84 82 00,...,NaN,NaN,NaN,"['shopping_mall', 'cafe', 'meal_delivery', 'su...",https://maps.google.com/?cid=3737344296213236355,17570.0,60.0,"Calle de Margarita de Parma, 1, Madrid",https://www.elcorteingles.es/centroscomerciale...,True
2,2,"[{'long_name': 'Zona', 'short_name': 'Zona', '...",OPERATIONAL,"[{'close': {'date': '2023-02-12', 'day': 0, 't...","['Monday: Closed', 'Tuesday: 12:00\u2009–\u200...",True,True,"Paseo de la, Zona, P.º de la Tierra de Melide,...",917 50 53 93,+34 917 50 53 93,...,NaN,True,True,"['restaurant', 'food', 'point_of_interest', 'e...",https://maps.google.com/?cid=14070834893686348892,599.0,60.0,"Zona, Paseo de la, Paseo de la Tierra de Melid...",https://www.casacorrochano.es/,NaN
3,3,"[{'long_name': 'Plaza de la Moraleja', 'short_...",OPERATIONAL,"[{'close': {'date': '2023-02-13', 'day': 1, 't...",['Monday: 1:00\u202fPM\u2009–\u200912:00\u202f...,False,True,"Pl. de la Moraleja, 28109 Alcobendas, Madrid, ...",916 25 25 00,+34 916 25 25 00,...,False,True,True,"['restaurant', 'food', 'point_of_interest', 'e...",https://maps.google.com/?cid=16618770644644484753,597.0,60.0,"Plaza de la Moraleja, Alcobendas",https://restauranteaspen.com/,True
4,4,"[{'long_name': '1', 'short_name': '1', 'types'...",OPERATIONAL,"[{'close': {'date': '2023-02-13', 'day': 1, 't...",['Monday: 12:30\u202fPM\u2009–\u20092:00\u202f...,False,True,"Pl. de la Moraleja, 1, 28109 Alcobendas, Madri...",916 58 52 97,+34 916 58 52 97,...,False,True,True,"['restaurant', 'food', 'point_of_interest', 'e...",https://maps.google.com/?cid=5931455114014290729,2378.0,60.0,"Plaza de la Moraleja, 1, Alcobendas",https://lamaquinalamoraleja.es/,True

In [20]:
places.drop('Unnamed: 0', axis=1, inplace=True)

In [21]:
places.shape

(3843, 37)

In [22]:
last_places_df = pd.concat([places, last_details_df], axis=0, ignore_index=True)

In [24]:
last_places_df = last_places_df.drop_duplicates(subset='result.place_id')

In [26]:
last_places_df.to_csv('last_places.csv')

# Getting coordinates

In [6]:
places = pd.read_csv('/Users/Usuario/demo/Ironhack/Final_Project/raw_data/google_data/brand_new_places.csv')

In [8]:
place_ids = places['result.place_id'].tolist()

In [9]:
len(place_ids)

6308

In [10]:
coordinates = get_place_details(place_ids)
coordinates.shape

(6308, 57)

In [13]:
coordinates.drop(columns=['html_attributions', 'status','result.secondary_opening_hours',
        'result.adr_address', 'result.current_opening_hours.open_now', 'result.icon','result.icon_background_color', 
        'result.icon_mask_base_uri', 'result.current_opening_hours.special_days',
       'result.permanently_closed','result.curbside_pickup',
       'result.editorial_summary.language','result.editorial_summary.overview'],axis=1, inplace=True)

In [14]:
coordinates.to_csv('coordinates.csv')

In [17]:
shorter_coordinates = coordinates[['result.geometry.location.lat','result.geometry.location.lng','result.place_id']]

In [18]:
shorter_coordinates.to_csv('shorter_coordinates.csv')